### ISSUE TITLE
If the "hello world service" for the API consumer tutorial has two gateways assigned, the clickable link does not work

### ISSUE THREAD

**Issue by gr-hovest-atb** [coatrack/coatrack#90]
This is about the tutorial for API consumers, where the consumer can test a generated IP key using a clickable link.This link does not work in case that two gateways are assigned to a service, as it contains two URLs separated by a comma. 

Probably reason: When generating the clickable link, a map of "proxies per api key" is used. This leads to the problem that in case of two gateways assigned to the "tutorial hello world service", then two values from the map will be returned, leading to a broken link including a comma between URLs (i.e. between map values).

This is directly related to #89 and probably those two issues could be solved together.

**Comment by perezdf** [comment]
```
    public String refreshApiKeys(@PathVariable("whichFragmentToLoad") String whichFragmentToLoad, Model model) {

        ServiceApi gettingStartedTestService = loadTestServiceForConsumerWizard();
        List<ApiKey> apiKeysForTestService = apiKeyRepository.findByLoggedInAPIConsumerAndServiceId(gettingStartedTestService.getId());

        // Gets the last Getting Started Test Service APIKey, as the Getting Started for Consumer can be used several times (there is size -1 because the array starts in element 0)
        ApiKey newApiKey = apiKeysForTestService.get(apiKeysForTestService.size() - 1);
```
Maybe this issues is already fixed?

**Comment by gr-hovest-atb** [comment]
@perezdf No, the code excerpt you posted is about another case: it solves the problem that "there are N _api keys_ for 1 service".

However, this issue is about "there are N _gateways_ for 1 service" and that is not yet fixed.
